language: cpp
compiler:
  - gcc
  - clang

before-install:
  - sudo apt-get update -qq
  - sudo apt-get install glew doxygen

install:
  - git submodule init
  - git submodule update

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
 git commit -m "Back to cmake v. 2.8"