language: cpp
compiler:
  - gcc
  - clang

before-install:
  - sudo apt-get update -qq
  - sudo apt-get install doxygen x11proto-xf86vidmode-dev

install:
  - git submodule init
  - git submodule update

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make