language: cpp
compiler:
  - gcc
  - clang

before-install:
  - sudo apt-get update -qq
  - sudo apt-get install glew

install:
  - git submodule init
  - git submodule update

before_script:
  - mv CmakeLists.txt CMakeLists.txt
  - mkdir build
  - cd build
  - cmake ..

script: make
